# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: tests

on:
  pull_request:
  push:

env:
  default-python: 3.8

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default-python }}
      - name: Upgrade pip, Install nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Lint
        run: |
          nox --error-on-missing-interpreters --non-interactive --session lint

  build-react-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
        include:
          - os: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build React app
        run: |
          cd termpair/frontend_src
          yarn install
          yarn build

  run-python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip, Install nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Execute Python Tests
        run: |
          nox --non-interactive --session test-${{ matrix.python-version }}
